/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#8582ff",
        "secondary": "#515c70",
        "error-container": "#f74b6d",
        "on-secondary": "#eff2ff",
        "surface-container-highest": "#d9dde0",
        "surface-tint": "#4a40e0",
        "error": "#b41340",
        "surface-variant": "#d9dde0",
        "surface-container": "#e5e9eb",
        "on-secondary-container": "#475266",
        "on-primary-fixed": "#000000",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#9795ff",
        "on-primary-container": "#14007e",
        "inverse-on-surface": "#9a9d9f",
        "inverse-surface": "#0b0f10",
        "tertiary-fixed-dim": "#c488ff",
        "on-tertiary-fixed": "#270048",
        "on-tertiary-fixed-variant": "#560094",
        "primary-container": "#9795ff",
        "background": "#f5f7f9",
        "outline-variant": "#abadaf",
        "on-secondary-fixed": "#354053",
        "secondary-container": "#d8e3fb",
        "on-primary": "#f4f1ff",
        "surface-container-low": "#eef1f3",
        "tertiary-dim": "#740ec2",
        "on-error": "#ffefef",
        "outline": "#747779",
        "on-surface-variant": "#595c5e",
        "surface": "#f5f7f9",
        "error-dim": "#a70138",
        "primary-dim": "#3d30d4",
        "surface-bright": "#f5f7f9",
        "secondary-dim": "#455064",
        "surface-container-high": "#dfe3e6",
        "on-error-container": "#510017",
        "primary-fixed-dim": "#8885ff",
        "tertiary-container": "#ce9bff",
        "secondary-fixed": "#d8e3fb",
        "secondary-fixed-dim": "#cad5ed",
        "on-background": "#2c2f31",
        "tertiary": "#8126cf",
        "tertiary-fixed": "#ce9bff",
        "on-tertiary-container": "#4a0080",
        "on-surface": "#2c2f31",
        "on-tertiary": "#fbefff",
        "on-primary-fixed-variant": "#1a0099",
        "primary": "#4a40e0",
        "on-secondary-fixed-variant": "#515c70"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
